fix: NULL appears first when order By DESC
subsquid/squid-sdk pull request #191
Opened 2023-07-26 08:51 UTC by justraman

2023-08-07 06:56 UTC, eldargab commented
Hey, this is a breaking change and it's non-obvious that it is always what users want!

I'm not against CLI flag enabling such behaviour, also would be nice to know how Hasura and postgraphile behave...

2023-08-07 11:04 UTC, justraman commented
Hey @eldargab , I see your point.  I just checked the Hasura and Postgraphile as mentioned
1. Postgraphile allows it by using an argument when initializing the engine `orderByNullsLast: true`
2. On the other hand, Hasura handles nullable fields differently by creating additional OrderBy options [desc_nulls_last, desc_nulls_first and default desc ](https://hasura.io/docs/latest/queries/postgres/sorting/)

Which one would you prefer?

2023-08-07 11:17 UTC, eldargab commented
Can we agree on 

```gql
query {
  list(orderBy: [foo_DESC_NULLS_LAST, bar_DESC, baz_ASC_NULLS_FIRST, qux_ASC]) {
    foo
    bar
  }
}
```

?

2023-08-07 11:24 UTC, eldargab commented
To elaborate:

With the flag option it is possible to have 2 similarly looking servers behaving completely differently. Also that approach is not flexible.

That leaves us with the need to extend the interface...

2023-08-07 11:27 UTC, justraman commented
> 

Absolutely!, I will work on it this week.

2023-08-07 11:36 UTC, eldargab commented
Great!

The very brief implementation guide will be

1. extend the [SortOrder](https://github.com/subsquid/squid-sdk/blob/ab1cae1eb6c9c4a34760f4fea09dff45c2f4065b/graphql/openreader/src/ir/args.ts#L85)
2. check and fix places where it is used :)

2023-08-09 21:23 UTC, justraman commented
@eldargab it's ready for review, i tried and tested locally.

2023-08-10 07:45 UTC, eldargab requested changes
Please include a change file as well

```bash
rush change -b origin/master
```

2023-08-10 07:45 UTC, eldargab commented on graphql/openreader/src/opencrud/orderBy.ts
> +                    if (properties[key].nullable || nullable) {
This check makes `nullable` -> `non-nullable` transition a breaking change. I would probably generate sort options regardless nullability.

2023-08-10 07:45 UTC, eldargab commented on graphql/openreader/src/ir/args.ts
> +export type SortOrder = 'ASC' | 'DESC' | 'ASC_NULLS_FIRST' | 'DESC_NULLS_LAST'
I'd use spaces here (`'ASC NULLS FIRST'`) to avoid introduction of regex replacement below

2023-08-11 11:38 UTC, merged